name: Run Unit Tests

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore EquipWatch/EquipWatch.sln
      
    - name: Set up environment variables
      run: |
        echo "SMTP=${{ secrets.SMTP }}" >> $GITHUB_ENV
        echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
        echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        echo "ADDRESS=${{ secrets.ADDRESS }}" >> $GITHUB_ENV
            
    - name: Build and run unit tests
      run: dotnet test EquipWatch/EquipWatch.sln 
